## Numpy array and basics


In [1]:
import numpy as np

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


#### list vs numpy array

In [5]:
py_list = [1, 2, 3, 4, 5]
print ('Python list multiplication by 2:', py_list * 2)
np_array = np.array([[1,2,3]])
print ('Numpy array multiplication by 2:', np_array * 2)

Python list multiplication by 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication by 2: [[2 4 6]]


##### Create array from scratch

In [10]:
zeros = np.zeros((2, 3))
print('2x3 array of zeros:\n', zeros)

ones = np.ones((3, 2))
print('3x2 array of ones:\n', ones)

full = np.full((2, 2), 7)
print('2x2 array filled with 7:\n', full)

random = np.random.rand(2, 3)
print('2x3 array of random numbers:\n', random)
sequuence = np.arange(0, 10, 2)
print('Sequence from 0 to 10 with step 2:\n', sequuence)

2x3 array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
3x2 array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
2x2 array filled with 7:
 [[7 7]
 [7 7]]
2x3 array of random numbers:
 [[0.15481564 0.66176491 0.66996618]
 [0.34400213 0.18370854 0.83821655]]
Sequence from 0 to 10 with step 2:
 [0 2 4 6 8]


#### Vector ,Matrix,tensor


In [11]:
vector = np.array([1, 2, 3])
print('Vector:\n', vector)

matrix = np.array([[1, 2], [3, 4]])
print('Matrix:\n', matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('Tensor:\n', tensor)

Vector:
 [1 2 3]
Matrix:
 [[1 2]
 [3 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print('Shape', arr.shape)
print('Number of dimensions', arr.ndim)
print('Size', arr.size)
print('Data type', arr.dtype)

Shape (2, 3)
Number of dimensions 2
Size 6
Data type int64
